import React from 'react'
import Logo from '../assets/Logo.jpg'
const Header = () => {
  return (
    <>
      <header className="mb-10 ">
        <div className="pt-5 bg-lime-900 p-4 pb-10">
          <img src={Logo} alt="" className="mx-auto"  />
        </div>

        <div className=" space-y-10 shadow-md p-5 bg-lime-900 text-white md:p-10 mt-2 rounded-lg">
          <h1 className="text-4xl md:text-4xl font-bold  text-center">
            Olam Intergated Consultance
          </h1>
          <p className="text-md font-bold">
            (A) Please take note that you need to apply for this before placing
            your orders, you will need to apply for the purchase permit order
            that will grant your access for purchase & assessment.
          </p>

          <div className="text-white mx-auto space-y-10 ">
            <h2 className="font-bold text-md ">
              (B) HERE WE HAVE THREE CATEGORIES OF REGISTRATION:
            </h2>
            <p className="grid w-mx space-y-5 text-sm font-bold ">
              <span className="">
                1. Major Distributorship Registration (PERMANENT AND FULL ACCESS
                TO THE COMPANY) ₦780,780 only. MINIMUM ORDER QUANTITY (600 Bags){' '}
              </span>
              <span>
                2. Retailer / Farmers Registration (VALID FOR 2 YEARS) ₦75,780
                MINIMUM ORDER QUANTITY (100 Bags){' '}
              </span>
              <span>
                3. End User Registration (ONE TIME PURCHASE) ₦35,780 Only.
                MINIMUM ORDER QUANTITY ( 50 Bags){' '}
              </span>
              <span>4. Raw Materials Supplier Registration, ₦185,000</span>
              <span>5. Services Registration, ₦225,000</span>
            </p>
            <p className="text-md font-bold text-white">
              (C) Once you apply for the purchase permit order, it takes 24
              hours of approval before gaining access for purchase. Once you
              apply for purchase permit order, you will receive a payment
              receipt and the successful purchase permit order form from us
            </p>

            <p className="text-md font-bold text-white ">
              (D) Duration for delivery is within 3 days after the
              acknowledgement receipt of deposit which will be generated by your
              pro-forma invoice. If there is any issue with your product, you
              can raise a refund, replacement or exchange request within 9 days
              of receiving the product.
            </p>
          </div>
        </div>
      </header>
    </>
  );
}

export default Header